package edu.depaul.ntessema.jaxrs.data.repository;

import edu.depaul.ntessema.jaxrs.data.model.Quote;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentSkipListMap;
import java.util.stream.Stream;

/**
 * This class simulates the persistent layer.
 * @author nardos
 */
public class SimpleQuotesRepository implements Repository<Quote, Integer> {

    /*
     * Quotes are stored in a map structure where the keys
     * are the ids and the values are the quotes.
     *
     * Why this particular map implementation is chosen:
     *
     * (1) A scalable concurrent ConcurrentNavigableMap implementation.
     * (2) Sorted according to the natural ordering of its keys.
     * (3) Expected average log(n) time cost for the containsKey, get, put and remove operations.
     * (4) Insertion, removal, update, and access operations safely execute concurrently by multiple threads.
     *
     * https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentSkipListMap.html
     */
    private final Map<Integer, Quote> quotes = new ConcurrentSkipListMap<>();

    private static SimpleQuotesRepository INSTANCE = null;

    private SimpleQuotesRepository() {

        /*
         * Create a quote object for each quote,
         * assign generated id for the object and
         * save it in the chosen data structure.
         */
        Stream.of(QUOTES).forEach(q -> {
            Quote quote = new Quote(q);
            /*
             * Id numbering begins from 1.
             * id = 1, 2, 3, 4, ...
             */
            final int id = 1 + quotes.size();
            quote.setId(id);
            quotes.put(id, quote);
        });
    }

    public static SimpleQuotesRepository getInstance() {
        if(INSTANCE == null) {
            synchronized (SimpleQuotesRepository.class) {
                if(INSTANCE == null) {
                    INSTANCE = new SimpleQuotesRepository();
                }
            }
        }
        return INSTANCE;
    }

    /**
     * Find a quote by its id.
     * @param id - cannot be null
     * @return quote with given id if it exists or null.
     */
    @Override
    public Quote findById(Integer id) {
        if(id == null) {
            throw new IllegalArgumentException("Id cannot be null");
        }
        return quotes.get(id);
    }

    @Override
    public Iterable<Quote> findAll() {
        List<Quote> all = new ArrayList<>();
        for(Map.Entry<Integer, Quote> q : quotes.entrySet()) {
            all.add(q.getValue());
        }
        return all;
    }

    @Override
    public Iterable<Quote> findAllById(Iterable<Integer> ids) {
        if(ids == null) {
            throw new IllegalArgumentException("Ids iterable cannot be null.");
        }
        List<Quote> iterable = new ArrayList<>();
        ids.forEach(id -> {
            if(quotes.get(id) != null) {
                iterable.add(quotes.get(id));
            }
        });
        return iterable;
    }

    /**
     * Saves a quote and returns the saved quote.
     *
     * The incoming quote will be assigned the next
     * id even if it already has a non-null id.
     *
     * @param quote - cannot be null.
     * @return the saved quote
     */
    @Override
    public Quote save(Quote quote) {
        if(quote == null) {
            throw new IllegalArgumentException("Null quote cannot be saved.");
        }
        /*
         * Generate a new id and assign to quote regardless of
         * the fact that it might already come with an id.
         *
         * This is important to save the id space.
         * If a user is allowed to choose a quote's id,
         * there is nothing preventing her from saving a
         * quote with an id of Integer.MAX_VALUE, which means that
         * there is no next integer to assign to the next quote...
         */
        final Integer id = 1 + quotes.keySet().stream().max(Comparator.naturalOrder()).orElse(0);
        quote.setId(id);
        quotes.put(id, quote);
        return quote;
    }

    /**
     * Find a quote by id, update its value,
     * and return the old quote object.
     *
     * If a quote with null or non-existent id is provided,
     * it will be assigned a new id and will be saved.
     *
     * @param quote - must exist and cannot be null
     * @return - the updated quote
     */
    @Override
    public Quote update(Quote quote) {
        if(quote == null) {
            throw new IllegalArgumentException("Quote cannot be null.");
        }
        Integer id = quote.getId();
        if(id == null || !quotes.containsKey(id)) {
            /*
             * If the incoming quote's id is null or does not
             * exist in the quotes data structure, the id of the returned
             * quote is different from that of the incoming quote
             * because it is generated by the quote access layer.
             *
             * TODO: Does this violate Idempotency?
             */
            return save(quote);
        }
        /*
         * A quote with the incoming quote's id exists.
         */
        Quote oldQuote = quotes.get(id);
        quote.setId(id);
        quotes.put(id, quote);
        /*
         * The returned quote has the same
         * id as that of the incoming one.
         */
        return oldQuote;
    }

    /**
     * Checks if a quote with given id exists.
     * @param id - cannot be null.
     * @return true if quote exists; false, otherwise.
     */
    @Override
    public boolean existsById(Integer id) {
        if(id == null) {
            throw new IllegalArgumentException("Id cannot be null");
        }
        return quotes.get(id) != null;
    }

    /**
     * Delete a quote by id.
     * @param id - cannot be null
     * @return true if a quote was removed; false, otherwise.
     */
    @Override
    public boolean delete(Integer id) {
        if(id == null) {
            throw new IllegalArgumentException("Id cannot be null.");
        }
        Quote removed = quotes.remove(id);
        return removed != null;
    }

    @Override
    public int count() {
        return quotes.size();
    }

    @Override
    public Set<Integer> getIds() {
        return quotes.keySet();
    }

    /*
     * The initial set of quotes.
     */
    private static final String[] QUOTES = new String[] {
            "Conscience does make cowards of us all.",
            "What does not destroy me makes me stronger.",
            "Everything has been figured out, except how to live.",
            "There is no fate that cannot be surmounted by scorn.",
            "There are so many dawns that have not yet broken.",

            //TODO:
            // Delete before submission these next quotes obtained from
            // https://www.forbes.com/sites/kevinkruse/2013/05/28/inspirational-quotes/#1770d77d6c7a

            "Life is about making an impact, not making an income. --Kevin Kruse",
            "Whatever the mind of man can conceive and believe, it can achieve. –Napoleon Hill",
            "Strive not to be a success, but rather to be of value. –Albert Einstein",
            "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.  –Robert Frost",
            "I attribute my success to this: I never gave or took any excuse. –Florence Nightingale",
            "You miss 100% of the shots you don’t take. –Wayne Gretzky",
            "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed. –Michael Jordan",
            "The most difficult thing is the decision to act, the rest is merely tenacity. –Amelia Earhart",
            "Every strike brings me closer to the next home run. –Babe Ruth",
            "Definiteness of purpose is the starting point of all achievement. –W. Clement Stone",
            "Life isn't about getting and having, it's about giving and being. –Kevin Kruse",
            "Life is what happens to you while you’re busy making other plans. –John Lennon",
            "We become what we think about. –Earl Nightingale",
            "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover. –Mark Twain",
            "Life is 10% what happens to me and 90% of how I react to it. –Charles Swindoll",
            "The most common way people give up their power is by thinking they don’t have any. –Alice Walker",
            "The mind is everything. What you think you become.  –Buddha",
            "The best time to plant a tree was 20 years ago. The second best time is now. –Chinese Proverb",
            "An unexamined life is not worth living. –Socrates",
            "Eighty percent of success is showing up. –Woody Allen",
            "Your time is limited, so don’t waste it living someone else’s life. –Steve Jobs",
            "Winning isn’t everything, but wanting to win is. –Vince Lombardi",
            "I am not a product of my circumstances. I am a product of my decisions. –Stephen Covey",
            "Every child is an artist.  The problem is how to remain an artist once he grows up. –Pablo Picasso",
            "You can never cross the ocean until you have the courage to lose sight of the shore. –Christopher Columbus",
            "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. –Maya Angelou",
            "Either you run the day, or the day runs you. –Jim Rohn",
            "Whether you think you can or you think you can’t, you’re right. –Henry Ford",
            "The two most important days in your life are the day you are born and the day you find out why. –Mark Twain",
            "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it. –Johann Wolfgang von Goethe",
            "The best revenge is massive success. –Frank Sinatra",
            "People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily. –Zig Ziglar",
            "Life shrinks or expands in proportion to one's courage. –Anais Nin",
            "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced. –Vincent Van Gogh",
            "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. –Aristotle",
            "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you. –Jesus",
            "The only person you are destined to become is the person you decide to be. –Ralph Waldo Emerson",
            "Go confidently in the direction of your dreams.  Live the life you have imagined. –Henry David Thoreau",
            "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me. –Erma Bombeck",
            "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.  –Booker T. Washington",
            "Certain things catch your eye, but pursue only those that capture the heart. – Ancient Indian Proverb",
            "Believe you can and you’re halfway there. –Theodore Roosevelt",
            "Everything you’ve ever wanted is on the other side of fear. –George Addair",
            "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. –Plato",
            "Teach thy tongue to say, 'I do not know,' and thous shalt progress. –Maimonides",
            "Start where you are. Use what you have.  Do what you can. –Arthur Ashe",
            "When I was 5 years old, my mother always told me that happiness was the key to life.  When I went to school, they asked me what I wanted to be when I grew up.  I wrote down ‘happy’.  They told me I didn’t understand the assignment, and I told them they didn’t understand life. –John Lennon",
            "Fall seven times and stand up eight. –Japanese Proverb",
            "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us. –Helen Keller",
            "Everything has beauty, but not everyone can see. –Confucius",
            "How wonderful it is that nobody need wait a single moment before starting to improve the world. –Anne Frank",
            "When I let go of what I am, I become what I might be. –Lao Tzu",
            "Life is not measured by the number of breaths we take, but by the moments that take our breath away. –Maya Angelou",
            "Happiness is not something ready made.  It comes from your own actions. –Dalai Lama",
            "If you're offered a seat on a rocket ship, don't ask what seat! Just get on. –Sheryl Sandberg",
            "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end. –Aristotle",
            "If the wind will not serve, take to the oars. –Latin Proverb",
            "You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground. –Unknown",
            "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained. –Marie Curie",
            "Too many of us are not living our dreams because we are living our fears. –Les Brown",
            "Challenges are what make life interesting and overcoming them is what makes life meaningful. –Joshua J. Marine",
            "If you want to lift yourself up, lift up someone else. –Booker T. Washington",
            "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. –Leonardo da Vinci",
            "Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless. –Jamie Paolinetti",
            "You take your life in your own hands, and what happens? A terrible thing, no one to blame. –Erica Jong",
            "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do. –Bob Dylan",
            "I didn’t fail the test. I just found 100 ways to do it wrong. –Benjamin Franklin",
            "In order to succeed, your desire for success should be greater than your fear of failure. –Bill Cosby",
            "A person who never made a mistake never tried anything new. – Albert Einstein",
            "The person who says it cannot be done should not interrupt the person who is doing it. –Chinese Proverb",
            "There are no traffic jams along the extra mile. –Roger Staubach",
            "It is never too late to be what you might have been. –George Eliot",
            "You become what you believe. –Oprah Winfrey",
            "I would rather die of passion than of boredom. –Vincent van Gogh",
            "A truly rich man is one whose children run into his arms when his hands are empty. –Unknown",
            "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.  –Ann Landers",
            "If you want your children to turn out well, spend twice as much time with them, and half as much money. –Abigail Van Buren",
            "Build your own dreams, or someone else will hire you to build theirs. –Farrah Gray",
            "The battles that count aren't the ones for gold medals. The struggles within yourself--the invisible battles inside all of us--that's where it's at. –Jesse Owens",
            "Education costs money.  But then so does ignorance. –Sir Claus Moser",
            "I have learned over the years that when one's mind is made up, this diminishes fear. –Rosa Parks",
            "It does not matter how slowly you go as long as you do not stop. –Confucius",
            "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. –Oprah Winfrey",
            "Remember that not getting what you want is sometimes a wonderful stroke of luck. –Dalai Lama",
            "You can’t use up creativity.  The more you use, the more you have. –Maya Angelou",
            "Dream big and dare to fail. –Norman Vaughan",
            "Our lives begin to end the day we become silent about things that matter. –Martin Luther King Jr.",
            "Do what you can, where you are, with what you have. –Teddy Roosevelt",
            "If you do what you’ve always done, you’ll get what you’ve always gotten. –Tony Robbins",
            "Dreaming, after all, is a form of planning. –Gloria Steinem",
            "It's your place in the world; it's your life. Go on and do all you can with it, and make it the life you want to live. –Mae Jemison",
            "You may be disappointed if you fail, but you are doomed if you don't try. –Beverly Sills",
            "Remember no one can make you feel inferior without your consent. –Eleanor Roosevelt",
            "Life is what we make it, always has been, always will be. Grandma Moses",
            "The question isn’t who is going to let me; it’s who is going to stop me. –Ayn Rand",
            "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. –Henry Ford",
            "It’s not the years in your life that count. It’s the life in your years. –Abraham Lincoln",
            "Change your thoughts and you change your world. –Norman Vincent Peale",
            "Either write something worth reading or do something worth writing. –Benjamin Franklin",
            "Nothing is impossible, the word itself says, “I’m possible!” –Audrey Hepburn"
    };
}
